name:                clean-architecture-with-functions
version:             0.1.0.0
github:              "githubuser/clean-architecture-with-functions"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/clean-architecture-with-functions#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- aeson
- base-compat-batteries

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  clean-architecture-with-functions-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clean-architecture-with-functions

tests:
  clean-architecture-with-functions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clean-architecture-with-functions
    - hspec
    - hspec-discover
    - QuickCheck
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover == 2.*